#!/bin/bash
#
# geomodel (Shell Script)
# 
# Objetivo: Gerar modelo da subsuperfície para o programa triseis do SU.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 22/03/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

# Scripts de padronização de mensagens de ajuda e erro
source mensagemAjuda.sh
source mensagemErro.sh

## Verificar se o usuário forneceu $1
if [ -z "$1" ]
then
	MENSAGEMERRO="Usuário não ofereceu parâmetros ao programa!\nDigite $(basename $0) -h para obter ajuda!"
	exibirMensagemErroProgramaFormatada "$(basename $0)" "1" "$MENSAGEMERRO"
fi

# Versão deste programa
VERSAO="Versão 1.0"

## Variáveis que armazenam mensagem de ajuda do programa
NOME_PROGRAMA="$(basename $0)"
DESCRICAO=" Gerar modelo da subsuperfície para o programa triseis do SU."
PARAMETROS="-h --help::Exibe essa tela de ajuda e sai
-v --version::Exibe a versão do programa e sai
-m --model::Gerar o modelo em arquivo binário
-i --image::Gerar imagem eps de modelo gerado com -m"
EXEMPLO_DE_USO="~$ $(basename $0) -m <nome do arquivo binário>
\t~$ $(basename $0) -i <arquivo gerado com a opção -m>
"

case "$1" in
	-h | --help) ## Exibe a ajuda
		clear
		exibirMensagemAjudaProgramaFormatada "$NOME_PROGRAMA" "$DESCRICAO" "$PARAMETROS" "$EXEMPLO_DE_USO"
		exit 0
	;;

	-v | --version) ## Exibe a versão do programa
		echo $VERSAO
		exit 0
	;;

	-m | --model) ## Gerar modelo com trimodel

		## Caso o usuário não fornecer um nome para o arquivo, gere um aleatório
		[ -z "$2" ] && {
			echo "Usuário não forneceu nome do arquivo, criando um nome..."
			MODEL_FILENAME=$(mktemp model-XXXX.bin)
			echo "Arquivo: $MODEL_FILENAME"
		}	
		
		trimodel xmin=0 zmin=0 xmax=12.0 zmax=3.5 \
			 1 xedge=0,2,4,6,8,10,12 \
			   zedge=0,0,0,0,0,0,0 \
			   sedge=0,0,0,0,0,0,0 \
			 2 xedge=0,12 \
			   zedge=0.3,0.25 \
			   sedge=0,0 \
			 3 xedge=0,12 \
			   zedge=0.7,0.45 \
			   sedge=0,0 \
			 4 xedge=0,2,4,6,8,10,12 \
			   zedge=1.2,1.2,1.3,1.4,0.7,1.05,1.2 \
			   sedge=0,0,0,0,0,0,0 \
			 5 xedge=0,2,4,6,8,10,12 \
			   zedge=1.7,1.7,1.8,2.0,1.1,1.45,1.8 \
			   sedge=0,0,0,0,0,0,0 \
			 6 xedge=0,2,4,6,8,10,12 \
			   zedge=2.2,2.2,2.3,2.5,1.6,1.9,2.2  \
			   sedge=0,0,0,0,0,0,0 \
			 7 xedge=0,2,4,6,8,10,12 \
			   zedge=2.7,2.7,2.8,2.9,2.2,2.4,2.7 \
			   sedge=0,0,0,0,0,0,0 \
			 8 xedge=0,2,4,6,8,10,12 \
			   zedge=3.5,3.5,3.5,3.5,3.5,3.5,3.5 \
			   sedge=0,0,0,0,0,0,0 \
			   sfill=0,0.1,0,0,0.39,0,0 \
			   sfill=0,0.4,0,0,0.31,0,0 \
			   sfill=0,0.9,0,0,0.28,0,0 \
			   sfill=0,1.5,0,0,0.25,0,0 \
			   sfill=0,2.0,0,0,0.55,0,0 \
			   sfill=0,2.4,0,0,0.44,0,0 \
			   sfill=0,3.0,0,0,0.16,0,0 \
			   kedge=1,2,3,4,5,6,7,8 \
			   >"${MODEL_FILENAME}"
	;;

	-i | --image) ## Gerar imagem EPS do modelo

		[ -z "$2" ] && {
			MENSAGEMERRO="Usuário não forneceu o modelo para gerar a imagem!\nDigite $(basename $0) -h para obter ajuda"
		exibirMensagemErroProgramaFormatada "$(basename $0)" "2" "$MENSAGEMERRO"

		}

		MODEL_FILENAME="$2"

		# Verificar se o arquivo está na pasta
		[ -f "$MODEL_FILENAME" ] || {
			MENSAGEMERRO="Arquivo $MODEL_FILENAME não encontrado!"
			exibirMensagemErroProgramaFormatada "$(basename $0)" "3" "$MENSAGEMERRO"
		}

		spsplot < "$MODEL_FILENAME" > "${MODEL_FILENAME%%.*}.eps" \
		gedge=0.5 gtri=2.0 gmin=0.2 gmax=1.0 \
		title="Modelo de camadas curvas" titlesize=20 labelz="Profundidade (km)" \
		labelx="Distancia (km)" labelsize=18 dxnum=1.0 dznum=0.5 wbox=15 hbox=8
	;;

	*)
		MENSAGEMERRO="Opção $1 Desconhecida!\nDigite $(basename $0) -h para obter ajuda"
		exibirMensagemErroProgramaFormatada "$(basename $0)" "4" "$MENSAGEMERRO"
	;;
esac
